- .pre-commit-config.yaml
- saspy/sas_magic.py
- setup.py
In addition to this change I also want to add pre-commit yaml files to keep mal formed code out of the project.
> add options to %%SAS magic for issue #4 in sas_kernel repo

- saspy/sas_magic.py
In a refactor I neglected to update iml and optmodel to match SAS.
I also stream lined the code slightly.
> fix iml and optmodel magics

- saspy/sasbase.py
- saspy/sascfg.py
This addresses issue #11 in sas_kernel, as well as pull request #2 for ssh support.
> add support for ssh and minor sascfg fixed

- saspy/sasbase.py
- saspy/sasproccommons.py
make change to handle string targets more explicitly by converting to a dictionary.
> improve handling of string targets

- saspy/sasproccommons.py
- saspy/tests/test_sasstat.py
this is primarily for statistics procedures that want more complicated model
selection and stopping rules
> add support for selection dictionary

- install.html
> authinfo doc

- saspy/doc/source/install.rst
- saspy/sasioiom.py
> add support for authinfo file. 

- saspy/sascfg.py
Quick fix of a couple typos in sascfg.py
> Fix typos in sascfg.py

- saspy/sasioiom.py
Signed-off-by: Willem Ligtenberg <willem.ligtenberg@cz.nl>
> Fix issue #78

- saspy/sasioiom.py
- saspy/sasiostdio.py
#87 is solved and closed with this fix. Haven't heard from #83, but my testing shows no issues and the default cases are cleaned up nicely and dtypes can be overridden along with any other read.csv() options being passed along, so merging into master. 
Tom
> Issues83and87

- saspy/sasbase.py
- saspy/sasioiom.py
- saspy/sasiostdio.py
> support ODS html style=

- saspy/tests/test_sasdata.py
- saspy/tests/test_sasets.py
- saspy/tests/test_sasml.py
- saspy/tests/test_sasstat.py
- saspy/tests/test_sasutil.py
- saspy/tests/util.py
This PR removes some spaces in assertion in the test_sasdata.py file, which were causing the tests to fail. It also introduces a utilities file that holds some util functions such as checking proc existence and proc licensing.
> Test fixes

- saspy/doc/source/advanced-topics.rst
- saspy/doc/source/getting-started.rst
- saspy/doc/source/install.rst
- saspy/doc/source/troubleshooting.rst
- saspy/sasbase.py
- saspy/sasioiom.py
- saspy/sasiostdio.py
Just a quick fix using `:%s/check you settings/check your settings/g` :)
> Grammatical fix for failure messages: 'double check you|your settings'

- saspy/sasbase.py
- saspy/sasioiom.py
- saspy/sasiostdio.py
Addresses issue #180 
Developer's Certificate of Origin 1.1
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; or
(c) The contribution was provided directly to me by some other
person who certified (a), (b) or (c) and I have not modified
it.
(d) I understand and …
> No mutable default arguments

- saspy/sasbase.py
Addresses issue #185 
There's a trailing whitespace and indentation change bundled with this.
Developer's Certificate of Origin 1.1
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; or
(c) The contribution was provided directly to me by some other
person who …
> Only make one request to provider during session init 

- saspy/__init__.py
- saspy/doc/source/install.rst
- saspy/sasbase.py
- saspy/sasexceptions.py
- saspy/tests/test_sasconfig.py
- saspy/tests/test_sasexceptions.py
> Allow users to store `sascfg_personal.py` in `$HOME/.config/saspy/`

- saspy/sas_magic.py
See #262 for details
This is just a prototype.
If some modifications needed, feel free to add.
> magic command to handle %%SAS <object>.<property>

- saspy/sasioiom.py
> Avoid import errors in some implementations

- saspy/sasbase.py
This allows for libraries to have multiple directories.
> Adds multiple paths to saslib function

- saspy/doc/source/configuration.rst
This commit fixes typos within documentation.
> Fix typos within documentation

- README.md
- saspy/doc/source/advanced-topics.rst
- saspy/doc/source/getting-started.rst
This commit fixes broken links caused by master to main branch name change.
> Fix broken links

- saspy/scripts/readme
This is a simple update to the sentence structure of the readme file.
> Update readme and correct typo
