- saspy/sasioiom.py
- saspy/sasiostdio.py
Added support for UNIX operating systems not having pty.h header in gnulibs, and that's why not being able to handle os.forkpty()
Python itself can handle this via pty module where such exception is done. Just have to use it in 2 of sasPY modules
Tested on AIX. Possible other OS affected Minix , HP-UX, IRIX, Solaris, BeOS
Issue #43
> add support for non linux UNIX OS (tested on AIX)

- saspy/doc/source/overview.rst
- saspy/sas_magic.py
- saspy/tests/test_sasmagic.py
This PR addresses https://github.com/sassoftware/saspy/issues/26, with thanks to @jld23 for assistance. I've updated the docs and added tests that spy on the `%%SAS` invocation to ensure the correct session object is used.
> Allow to share saspy session with cell magics

- saspy/doc/source/install.rst
- saspy/sascfg.py
- saspy/sasiostdio.py
- saspy/tests/test_sasconfig.py
I've found that using the SSH connection option is limited in my use cases when connecting to a server over VPN, or in any situation where (A) I need to use an alternate SSH port, or (B) my local machine cannot be accessed directly by the remote machine.
I added a couple of options to the ssh configuration to help with both of these cases:
- **port** - an alternative remote ssh port
- **tunnel** - this solves a problem that was breaking basic pandas <-> SAS functionality when a firewall or security configuration blocks the remote server from accessing arbitrary ports on the local machine; `sasdata2dataframe` needs to open a local port for streaming data in from the SAS session, but the remote machine could not reach it. If you pass a `tunnel` port number, it will now establish a reverse …
> Add options for alternate ssh port and reverse tunnel

- setup.py
Pre-commit is a dev tool used to run quality checks before commiting.
It should not be in the main dependencies of the application.
Since there is no pre-commit config file, (.pre-commit-config.yaml)
I've taken the liberty to remove it altogether.
Fixes #74
> remove pre-commit dependency

- saspy/__init__.py
- saspy/sasbase.py
- saspy/sastabulate.py
Fix for #145 
For the one use of unpacking 2 dicts as a function argument (a capability added in python3.5), this PR swaps in a common use of ChainMap (part of the collections module, standard lib) for alternative syntax that is compatible with python3 prior to 3.5. 
I've run the tests successfully on 3.4 after this change. 
(I'm still interested in pursuing something like Travis CI for this library so that all commits can undergo automated testing against the array of python versions supported, to spot any compat gaps - but that would be tricky since the tests use live connections to a SAS session, rather than mocks etc. Perhaps some offline-only tests could be added that simply ensure the library fully imports without error, and those could be run on every python version supported as …
> fix tabulate code compatibility for python3 < python3.5

- saspy/sasViyaML.py
- saspy/sasml.py
- saspy/sasproccommons.py
- saspy/sasqc.py
- saspy/sasstat.py
- saspy/sastabulate.py
- saspy/sasutil.py
Each of the files changed was calling the root logger directly, this change fixes that so that each file correctly uses it's own logger.
Signed-off-by: Wesley Rogers <wsrogers3@catamount.wcu.edu>
> Moved direct calls to logging to each class's existing logger instead

- saspy/sascfg.py
The config file previously contained a hard-coded link to saspyiom.jar at: "C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\saspyiom.jar"
This will break if the user installed SASPy in *any way* other than through Anaconda3 with the default install path, and thus really should not be hard-coded like this.  This changes the config file to look for saspyiom in the same directory that the config file is being read from by accessing the __file__ attribute of the config file.
> Removed the hard-coded link to saspyiom.jar

- saspy/__init__.py
- saspy/sasbase.py
- saspy/sasexceptions.py
- saspy/tests/test_sasexceptions.py
Reference issue #218 
Initial commit to add exceptions instead of printing debug statements.
A note about 9bb0441: This seems like a scarier change than it really is. The diff is a bit messy.  The gist of this commit is that since we halt execution now instead of setting `_io = None`, we no longer need to say: `if self._io.pid`.  Likewise, since `_io.pid` should be set by the time we get here, there is no reason to handle the `AttributeError`.  If for whatever reason an attribute is **not** set, it's probably better to stop here instead of setting `_io = None`.  I'm happy to revisit this commit if you feel the exception handling is necessary.
> Add SASConfigNotValidError and SASIONotSupportedError

- saspy/tests/test_pandas.py
- saspy/tests/test_sasdata.py
- saspy/tests/test_sassession.py
Refactor some unit tests and note places that need additional revisions in the future.
Major changes include renaming tests to be more descriptive of their purpose, isolating asserts so that only one occurs per test, and moving some repeated Python/SAS code to a function or variable to improve readability or performance.
* Updated `TestPandasDataFrameIntegration` to only `assert` once per test.
* Updated test case to store `test_data` `SASdata` object as attribute for frequent access.
* Added light documentation.
* Renamed test functions to indicate purpose.
* Marked potential revisions with `FIXME`.
* Updated `TestSASsessionObject` to only `assert` once per test.
* Added light documentation.
* Renamed test functions to indicate purpose.
* Moved some tests to other modules.
* Updated …
> Unittest Updates

- saspy/sascfg.py
- saspy/sasexceptions.py
- saspy/sasiocom.py
The Java IOM access method supports reading username/password credentials from a ~/.authinfo file.  The spec for this file can be found here: https://documentation.sas.com/api/docsets/authinfo/9.4/content/authinfo.pdf.
This file uses the following format:
```
AUTHKEY username USERNAME password PASSWORD
```
Where the user can define the `AUTHKEY`, `USERNAME`, and `PASSWORD` attributes.
This PR was spawned from a comment in issue #237
> Add support for ~/.authinfo to IOMCOM

- saspy/sasbase.py
- saspy/sasiocom.py
- saspy/sasiohttp.py
- saspy/sasioiom.py
- saspy/sasiostdio.py
adding the ability to create data sets in an encoding other than session encoding, on df2sd(..., outencoding='sas_encoding_value'). This also adds the 'encoding' key in the dsopts for SASdata objects, which it will use when reading or writing back out again.
> Outencoding

- saspy/sasbase.py
- saspy/tests/test_pandas.py
Implemented a method in SASsession that converts the column-names of a Pandas DataFrame to SAS compatible column names using the same features as the SAS validvarname option. Supports versions V7, V6, UPCASE, and ANY. Unit tests have been added to test_pandas. 
Signed-off-by: Michael Senter <dmsenter89@gmail.com>
> Validvarname

- saspy/sasiohttp.py
Currently the user has to enter 'authcode' or 'userid' before they can continue.
I modified the code to make 'authcode' the default, if the user submits and empty string, authcode is assumed
The other change by passes all the prompting is the user provides an authcode.
Both changes are contained in the one file.
> make authcode default; simplify prompting if authcode supplied

- saspy/sasbase.py
Add __enter__ and __exit__ methods to SASSession to make it into a context manager, i.e. one can use
with SASSession() as sas_session:
....
> Allow SASSession to be used as a context manager

- saspy/scripts/run_sas.py
This PR makes run_sas.py accpect more than one SAS file, e.g., 
- `./run_sas.py -s example_1.sas example_2.sas`
- `./run_sas.py -s autoexec.sas example_2.sas`
saspy or run_sas doesn't honor `autoexec.sas` automatically which is different with SAS V9 in batch mode. Our projects use `autoexec.sas` and a project level setting SAS file to manange project settings. We have to using `%include` in each file if we call `run_sas`. It makes the code complicated and `%include` can't includes the remote file which might not be the updated one.
In case we are using IOM with Workspace server (for example, SAS EG), after the PR, `run_sas` can source local copy files which is different to `%inclue` which source the one the server.
It makes the `run_sas` a kind workable solution using in the task in …
> run_sas: to accept more than one SAS file

- saspy/sasproccommons.py
Changed the STAT and ETS default procopts to be `plots=all` instead of `plot=all`, which is the current SAS syntax default. This fixes #516. Re-ran unittests for both STATS and ETS - both passed as before.
> Update Plots Procopts

- saspy/tests/test_sasstat.py
Prefixed all tests with `test_` so that they will run with the unittests. This revealed some issues with the tests that I have fixed, including missing imports and tests that called the wrong functions. I also updated the messages to print out a useful error message in the event of a failed test. A skip has been added to `test_regResult4` that deserves further investigation - the test fails due to the function returning a NoneType. When I manually run this scenario in Jupyter, I also get the NoneType _but_ the output displays the HTML correctly as expected. The test `test_strdset2` is skipped because it doesn't seem to function properly. 
This PR fixes #515 .
> Improve Unittest File for STATS Products

- saspy/sasstat.py
The existing PROC FACTOR implementation in SASPy included two incorrect statements while omitting part of the accepted syntax. This PR updates the function implementation to match the PROC's syntax as found in the [documentation](https://go.documentation.sas.com/doc/en/pgmsascdc/9.4_3.4/statug/statug_factor_syntax.htm):
After making these changes, the STAT unit tests were run and passed as before.
> Update PROC FACTOR Implementation

- saspy/sasbase.py
- saspy/tests/test_symget.py
In the current version, symget gets an empty string and then crashes trying to convert it to an int.
In this version it crashes with a helpful error message as to what happened including a guess at the cause that an end-user might understand (that the session is dead).
> Improved error message when calling 'symget' on a dead session.

- saspy/doc/source/configuration.rst
Changed the documentation link from a version specific link to a link that always resolved into the most current version of the documentation.
> Change documentation link

- saspy/sasioiom.py
Changes to the sasioiom module:
1. In order to afterwards read files more efficiently using distributed frameworks such as Spark, I added an option to write the parquet file partitioned. 
2. Further, I added an option to add static columns to the final file. This is usefull when the goal is to union tables with the same schema, i.e. add a "year" column for tables storing data from different years.
3. Added parameters to control chunk and partition size  
@tomweber-sas  I won't get to it this week, but since you already did the integration into the other IO modules. If you accept these changes, I could add them into the other modules too. I could either do it in this pull request or we open a new one... Or you do it yourself. However you like.
Signed-off-by: Rainer Mensing …
> add partitioning, static columns and parameterization options

- saspy/sasbase.py
- saspy/sasioiom.py
Hello @tomweber-sas ,
I think we closed the testing of our sasdata2parquet staging method (insofar as we have merged this version into our productive workflow, so it should better work as expected haha).
The main visible change in this version is that the timestamps in the final parquet file will be the timestamps that can be found in sas. This also means, however, that loading the parquet with pandas will lead to OutOfBounds timestamp issue when very large (positive or negative) timestamps are contained in it. 
In this case, the user will need to develop a custom "safely_load_pandas" method that parses the affected columns. But this is still better than just coercing the timestamp to be null by default. Anyways, the raison d'être of the sasdata2parquet method are scenarios where the Data …
> UPDATE: preserve sas timestamps & pass through pyarrow kwargs

- saspy/sasproccommons.py
Fixed the string in saspy/sasproccommons.py:398 to no longer contain an invalid escape sequence.
See some documentation in https://docs.astral.sh/ruff/rules/invalid-escape-sequence/.
As far as I can tell this only caused deprecation warnings since python3.6 and no actual errors.
Signed-off-by: Stefan Eysoldt <stefan.eysoldt@deutsche-boerse.de>
> Fix deprecated warning for invalid escape sequence
